# Generated by Django 4.2.7 on 2023-11-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('url', models.URLField(max_length=500, verbose_name='상품 URL')),
                ('image_url', models.URLField(max_length=500, verbose_name='이미지 URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품들',
            },
        ),
    ]
